name: cronjob

# Controls when the action will run. Triggers the workflow once every day at 14:00 UTC
on:
  schedule:
    - cron: '00 14 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Run main
      run: |
        $CONDA/bin/python main.py ${{secrets.USERNAME}} ${{secrets.PASSWORD}}  
